# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  back:
    image: node
    restart: always
  front:
    image: node
    restart: always
  koj:
    image: node
    restart: always

